AllCops:
  TargetRubyVersion: 2.1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
Style/YodaCondition:
  Enabled: false
